### ISSUE TITLE
Please make a release on haxelib

### ISSUE THREAD

**Issue by andraaspar** [nadako/hxjsonast#12]
The last published version is 5 years old, and the recent pull request #11 fixed an important issue for Haxe 4 users. When installing hxjsonast as a dependency of another project, haxelib / lix will install the 5 years old published version by default. This means broken functionality for Haxe 4 users. Please consider making a release on haxelib to let users get the latest version of this great library by default. Thank you for your efforts.

**Comment by nadako** [comment]
Done. The tests seems to pass still, so let's hope it works :)
